api-test/Advanced Fees Management.postman_collection.json, openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleAttribute.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CiBundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
- Add `getBundleCreditorInstitutions` operation
- Add `getBundleCreditorInstitutionDetails ` operation
- Local run, `mvn package`
=> [PPR-359] feat: add operation for bundle (PSP)

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java, src/main/java/it/pagopa/afm/marketplacebe/model/offer/BundleCiOffers.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java
=> fix getOffers

src/main/java/it/pagopa/afm/marketplacebe/entity/CiBundle.java, src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CiBundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
Fixed:
- createBundleDetails
- updateBundleDetails
- removeBundleDetails
according to the [task](https://pagopa.atlassian.net/browse/PPR-373)
=> [PPR-348] Fix CUD CIBundle

src/main/java/it/pagopa/afm/marketplacebe/config/WebMvcConfiguration.java, src/main/java/it/pagopa/afm/marketplacebe/entity/Touchpoint.java, src/main/java/it/pagopa/afm/marketplacebe/model/AppCorsConfiguration.java, src/main/resources/application-local.properties, src/main/resources/application.properties
=> feat: CORS

.devops/azure-templates/maven-versioning.yml, src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
=> Fix ID PSP

docker/applicationinsights.json, docker/run.sh
=> fix: add docker required files

doc/entities.puml, src/main/java/it/pagopa/afm/marketplacebe/model/request/CiBundleSubscriptionRequest.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java, src/main/java/it/pagopa/afm/marketplacebe/util/CommonUtil.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
- add check to create bundle request
- unit tests
A bundle subscription request is acceptable if and only if the public bundle is not expired.
=> [PPR-345] Rule R7

src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Rule R10:
- set validityDateTo to now when CI deletes a bundle subscription
=> [PGEC-41] Rule R10

src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java, src/main/java/it/pagopa/afm/marketplacebe/util/CommonUtil.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java
Rule R12:
- a CI cannot accept or request a bundle subscription if its validityDateTo is before or equal to now.
=> [PGEC-43] Rule R12

src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java
=> [PGEC-42] Rule R11

src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/java/it/pagopa/afm/marketplacebe/service/CalculatorService.java, src/main/java/it/pagopa/afm/marketplacebe/task/CalculatorTaskExecutor.java, src/main/resources/application-local.properties, src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
=> Bug fix payment amount range

src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
CiBundle payment amount should be lower than Bundle one
=> [PGEC-50] Rule R15

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml
=> fix AFM_CALCULATOR_HOST

.devops/deploy-pipelines.yml
The purpose of this PR is to fix `skip` into CD pipeline ( tnx @jacopocarlini  )
upd : 
- `deploy-pipelines.yml`
=> fix: Skip into CD pipeline

src/main/java/it/pagopa/afm/marketplacebe/task/CalculatorDataTaskExecutor.java
=> fix azurite

helm/values-prod.yaml, helm/values-uat.yaml
=> fix cpu limit value

.github/workflows/anchore.yml, .github/workflows/update_infra.yml, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/resources/application-local.properties, src/main/resources/application.properties, src/test/resources/application.properties
=> fix deploy

api-test/AFM Marketplace.postman_collection.json, src/main/java/it/pagopa/afm/marketplacebe/controller/TouchpointController.java, src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/TouchpointService.java, src/test/java/it/pagopa/afm/marketplacebe/service/TouchpointServiceTest.java
- added check on touchpoint before delete
=> feat: [PGEC-103] Check on touchpoint delete

api-test/AFM Marketplace.postman_collection.json, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/config/MappingsConfiguration.java, src/main/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeController.java, src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java, src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertBundleToPspBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleInfo.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/model/paymenttype/PaymentType.java, src/main/java/it/pagopa/afm/marketplacebe/model/paymenttype/PaymentTypes.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/java/it/pagopa/afm/marketplacebe/service/PaymentTypeService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/PaymentTypeServiceTest.java
- get payment types
- get payment type by name
=> feat: [PAGOPA-65] Payment types

openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/config/MappingsConfiguration.java, src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java, src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/model/paymenttype/PaymentTypes.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/resources/application-local.properties, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- added new method to create bundles by list
- massive bundles creation
- manual and junit test
=> [PAGOPA-591] create bundle by list

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- added payment type null management
- before the change the paymentType null was valued as ANY which is a value not allowed by ApiConfig
Manual test and Junit test
=> [PAGOPA-722] payment type null: added payment type null management

src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java
- abi not nullable
- idCdi nullable
=> fix: [PAGOPA-767] Nullable field

src/main/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeController.java, src/main/java/it/pagopa/afm/marketplacebe/entity/PaymentType.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/java/it/pagopa/afm/marketplacebe/service/PaymentTypeService.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/PaymentTypeServiceTest.java
- added sync for payment types
=> [PAGOPA-731] CRUD sync payment type

src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
- allowed private bundle type in createBundleRequest
- new business rule
- junit test
=> feat: [PAGOPA-883] allowed private bundle type

.github/workflows/deploy_with_github_runner.yml
=> fix runner

helm/Chart.lock, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: Helm pod affinity

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/java/it/pagopa/afm/marketplacebe/task/ValidBundlesTaskExecutor.java
- created an ad hoc query to extract valid bundles
- modified date control mode on bundle creation and update
- a newly created bundle is moved to the valid bundles collection even though the validity start date is still in the future
- manual and junit test
=> bug: [PAGOPA-1445] fix valid bundles

.github/workflows/code_review.yml, .github/workflows/update_code.yml, Dockerfile, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/java/it/pagopa/afm/marketplacebe/task/ValidBundlesTaskExecutor.java
depends on: [fix valid bundles](https://github.com/pagopa/pagopa-afm-marketplace-be/pull/82)
- config for java 17
- sonar has deprecated java 11
- manual and junit test
- [DEV deploy](https://github.com/pagopa/pagopa-afm-marketplace-be/actions/runs/7609668488)
=> feat: [PagoPA-1464] - upgrade to java17

Dockerfile, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml
Changing dockerfile to log application insights
The old dockerfile was not working properly with application insights
Manually
=> Pagopa 1481 sviluppo upgrade ai with java 17

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/repository/CosmosRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
added the number of total pages in the `GET /bundles`
=> [VAS-682] total pages

src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java
Fixing delete of specific bundle
Fix necessary to be able to successfully delete a specific bundle
Manually
=> PAGOPA-1539 fixing marketplace delete bundle

src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Creating an attribute for a ciBundle, the correlated bundle should be PRIVATE or PUBLIC
This fix was requested by BO for the correct functionality of the system
Manually and through junit
=> PAGOPA-1636 create attribute filter private and public

src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Fixing the following issue: when updating a bundle, the check would always stop if another bundle with the same configuration was found, even if it was the same bundle
This fix was needed for the correct functionality of the application and the correct integration in BO
Manually and through junit tests
=> PAGOPA-1639 update and create bundle analyze fix

openapi/generate_openapi.sh, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRequestRepository.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CiBundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/OpenApiGenerationTest.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Adding filter by ci fiscal code and pagination to api GET /psps/{idpsp}/bundles/{idbundle}/creditorInstitutions
This addition was needed by BO for the correct implementation of the software
Manually and through junit tests
=> Pagopa 1614 afm marketplace get bundle

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java, src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CiBundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/controller/CiControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Adding API GET /cis/{cifiscalcode}/pspBusinessName/{pspBusinessName}, needed by BO
This addition was needed by BO for the GEC integration
Manually and through JUNIT
=> Pagopa 1619 sviluppo afm market place ricerca bundle per psp company name

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/config/MappingsConfiguration.java, src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertCIBundleTCIBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/CiBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/model/offer/BundleCreditorInstitutionResource.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- updated response model for `GET /{idpsp}/bundles/{idbundle}/creditorInstitutions` and `GET /{idpsp}/bundles/{idbundle}/creditorInstitutions/{cifiscalcode}`
- added specific converter for service response
[VAS#945](https://pagopa.atlassian.net/browse/VAS-945)
=> [VAS-945] chore: Update get bundle ci details API

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/model/request/PublicBundleRequest.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
- fixed bundle request model mapping
=> [VAS-1005] fix: Bundle request model mapping

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/HomeController.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CosmosRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/HomeControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/repository/CosmosRepositoryTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- added `validFrom` query to GET /bundle API
- created dedicated query to fetch data
- updated unit test
=> [VAS-1007] feat: Add validity date param

src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleRequestServiceTest.java
- added check for attributes with null transfer category in public bundle requests, only one attribute can be specified if the attribute has null transfer category
- updated unit tests
=> [VAS-1034] feat: Add check on create public bundle request

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
Adding initialization of attributes list when ci accepts an offer by a psp. In addition, adding protection when creating an attribute.
Change needed in order to not cause a 500 null pointer exception when creating a new attribute.
Manually and through junit tests.
=> PAGOPA-1759 fixing null attributes when accepting an offer

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/config/SwaggerConfig.java, src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleOfferRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/java/it/pagopa/afm/marketplacebe/util/CommonUtil.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java, src/test/resources/application.properties
- updated `GET /psps/{idpsp}/offers` API with
- `ciTaxCode` parameter
- `idBundle` parameter
- valid page info in response
[VAS#1075](https://pagopa.atlassian.net/browse/VAS-1075)
=> [VAS-1075] feat: Update get offers API

src/main/java/it/pagopa/afm/marketplacebe/config/SwaggerConfig.java
=> fix: Swagger config

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/BundleController.java, src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java, src/main/java/it/pagopa/afm/marketplacebe/controller/HomeController.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleOfferRepository.java, src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CosmosRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/BundleControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/controller/CiControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/controller/HomeControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/repository/CosmosRepositoryTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- added API `GET /bundles/{id-bundle}` to retrieve bundle details for CI
- fixed API `GET /cis/{ci-fiscal-code}/offers` in order to correctly handle pagination and added `bundleName` filter parameter
- updated API `GET /cis/{ci-fiscal-code}/bundles`  with `bundleName` filter parameter
- updated unit tests
[VAS#1080](https://pagopa.atlassian.net/browse/VAS-1080)
=> [VAS-1080] feat: Add get bundle detail API for CI

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/CiController.java, src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java, src/main/java/it/pagopa/afm/marketplacebe/model/request/CiBundleAttributeModel.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleOfferService.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleRequestService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/CiControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleOfferServiceTest.java
- updated `POST /cis/{ci-fiscal-code}/offers/{id-bundle-offer}/accept` to receive a request body and to create bundle attributes when accepting private bundle offers
- fixed error message on public bundle request reject
- updated unit tests
[VAS#1105](https://pagopa.atlassian.net/browse/VAS-1105)
=> [VAS-1105] feat: Update accept offer API

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- added `forceUpdate` parameter in update bundle API
=> feat: Added force update bundle parameter

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/BundleController.java, src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java, src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertBundleToPspBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CosmosRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/BundleControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/repository/CosmosRepositoryTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- added new parameter `expiredAt` to `GET /bundles` API
- added `idPsp` field in `GET /bundles` API response
- removed contraint on limit
[VAS-1109](https://pagopa.atlassian.net/browse/VAS-1109)
[VAS-1109]: https://pagopa.atlassian.net/browse/VAS-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-1109] feat: Update get bundles API

openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/entity/Bundle.java, src/main/java/it/pagopa/afm/marketplacebe/mapper/ConvertBundleToPspBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/BundleRequest.java, src/main/java/it/pagopa/afm/marketplacebe/model/bundle/PspBundleDetails.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/main/java/it/pagopa/afm/marketplacebe/task/ValidBundlesTaskExecutor.java, src/test/java/it/pagopa/afm/marketplacebe/TestUtil.java
This feature is required to give PSPs the opportunity to create bundles not valid for carts payments, furthermore it can avoid situation where bundles configured on stations with `v1` primitives are used to pay carts (this case is not allowed and causes payments errors)
=> [PAGOPA-1877] feat: cart bundle management

src/main/java/it/pagopa/afm/marketplacebe/repository/BundleOfferRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- fixed remove bundle logic to delete all related request and offers that have not been already accepted or rejected
Avoid pending request/offer to a deleted bundle
[VAS#1102](https://pagopa.atlassian.net/browse/VAS-1102)
=> [VAS-1102] fix: Remove bundle logic 

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi-technical-support.json, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/controller/PspController.java, src/main/java/it/pagopa/afm/marketplacebe/repository/CosmosRepository.java, src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PspControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/repository/CosmosRepositoryTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- Modified PSP's Bundles' list API
- Added new param to order bundles by maxPaymentAmount
- Added new params to filter bundles by paymentAmount
- Added new params to filter bundles by validity dates
- Improved page info with `totalItems` value
- Updated unit tests
[PPANTT-99](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-99)
[PPANTT-99]: https://pagopa.atlassian.net/browse/PPANTT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-99] feat: New filters PSP bundles' list

src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- Add a case for creation of a new bundle with the same configuration as another one, but with an id_channel that ends with _ONUS
The system must support adding bundles with the same configuration but with channel IDs differentiated by the suffix _ONUS.
Unit test
=> [PIDM-61] check transferCategoryList overlap (handle onus case)

src/main/java/it/pagopa/afm/marketplacebe/service/BundleService.java, src/test/java/it/pagopa/afm/marketplacebe/service/BundleServiceTest.java
- Include bundle type check in transfer category list validation
This PR relaxes the validity checker for transfer categories, allowing bundles to be loaded even if they have the same transfer categories, as long as they are private.
Unit Test.
=> [PIDM-61] Include bundle type check in transfer category list validation

.github/workflows/code_review.yml, .gitignore, utilities/patchOnUsBundles/package.json, utilities/patchOnUsBundles/script.js
- Defined script to patch all bundles with new field onus
- Bump GHA code review version
[PAGOPA-2659](https://pagopa.atlassian.net/browse/PAGOPA-2659?atlOrigin=eyJpIjoiNzUxNjk0NzE2MTZiNGQwYmI5NTcxOTg5YzgyODI1NDQiLCJwIjoiaiJ9)
[PAGOPA-2659]: https://pagopa.atlassian.net/browse/PAGOPA-2659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [PAGOPA-2659] Define script to patch all bundles with new field onus

.identity/00_data.tf, .identity/03_github_environment.tf, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi-technical-support.json, openapi/openapi.json, pom.xml
Update pat token value
Needed in order to unlock deploy
Manually
=> fix: update pat token secret in repo

src/main/java/it/pagopa/afm/marketplacebe/repository/BundleRepository.java
- updated valid bundle query to include bundles expiring today (`>=`)
[PIDM-631](https://pagopa.atlassian.net/browse/PIDM-631)
Updated valid bundle task to include bundles expiring today
[PIDM-631]: https://pagopa.atlassian.net/browse/PIDM-631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PIDM-631] fix: Valid bundle query

openapi/openapi-technical-support.json, openapi/openapi.json, src/main/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeController.java, src/main/java/it/pagopa/afm/marketplacebe/exception/AppError.java, src/main/java/it/pagopa/afm/marketplacebe/model/paymenttype/PaymentTypeRequest.java, src/main/java/it/pagopa/afm/marketplacebe/service/PaymentTypeService.java, src/test/java/it/pagopa/afm/marketplacebe/controller/PaymentTypeControllerTest.java, src/test/java/it/pagopa/afm/marketplacebe/service/PaymentTypeServiceTest.java
Add create and delete payment method api
Needed in order to create and delete payment methods
Manually and through junit
=> chore: add payment method crud apis PIDM-709

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi-technical-support.json, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/afm/marketplacebe/model/paymentmethods/enums/PaymentMethodGroup.java
- Adding new payment methods values
Needed in order to perform a more in depth performance test
=> Pagopa 3200
